# Generated by Django 4.1.5 on 2023-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='flavor',
            field=models.CharField(choices=[('Life_changing', 'Life-changing'), ('Burstin', 'Bursting'), ('Hmmm', 'Hmmmm'), ('Need_salt', 'Needs salt'), ('Air', 'Air has more flavor')], max_length=15),
        ),
    ]
